#!/usr/bin/env python3
"""Stage 5: render LaTeX includes from CSVs + numbers.json.

Writes two kinds of files:
  1. code/paper/numbers.tex
     One \\newcommand per scalar in numbers.json. main.tex \\input{numbers.tex}
     and refers to e.g. \\OutsideGRegRCorr instead of hard-coded "0.62".
  2. code/paper/tables/<name>.tex
     Pre-formatted LaTeX table body for every CSV in out/tables/. main.tex
     \\input{tables/tab_main_gap.tex} (etc.) inside its own table environment.

Usage::
    python code/scripts/05_render_tex.py --config pipeline.yaml \\
        --analysis-dir out/ --paper-dir code/paper/

In --mock mode, reads from the mock_results bundle and emits red-italic
"\\mockval{...}"-wrapped values (matches the existing main.tex style).
"""
from __future__ import annotations
import argparse, csv, json, re, sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


# ─────────────────────────────────────────────────────────────────────
# numbers.json → \newcommand
# ─────────────────────────────────────────────────────────────────────
NUMBER_TO_MACRO = {
    "n_models":                      "TBNumModels",
    "n_full_problems":               "TBNumFullProblems",
    "n_hard_problems":               "TBNumHardProblems",
    "outside_g_r":                   "OutsideGRegRCorr",
    "outside_g_n":                   "OutsideGRegN",
    "outside_g_p":                   "OutsideGRegPValue",
    "outside_g_ci_lo":               "OutsideGRegCILo",
    "outside_g_ci_hi":               "OutsideGRegCIHi",
    "early_drift_cum_patch_delta":   "EarlyDriftCumPatchDelta",
    "early_drift_outside_g_delta":   "EarlyDriftOutsideGDelta",
    "early_drift_blame1_delta":      "EarlyDriftBlameOneDelta",
}


def render_numbers(numbers: dict, out_path: Path, mock: bool) -> None:
    lines = ["% AUTO-GENERATED by code/scripts/05_render_tex.py — DO NOT EDIT.",
             "% Edit out/analysis/numbers.json (real) or",
             "% code/mock_results/mock_bundle.json (mock) instead.", ""]
    for key, macro in NUMBER_TO_MACRO.items():
        val = numbers.get(key)
        if val is None:
            text = r"\mockval{TBD}" if mock else r"\textbf{??}"
        elif isinstance(val, float):
            text = f"{val:.3f}".rstrip("0").rstrip(".") if val < 1 else f"{val:.2f}"
            if mock: text = f"\\mockval{{{text}}}"
        else:
            text = str(val)
            if mock: text = f"\\mockval{{{text}}}"
        lines.append(f"\\newcommand{{\\{macro}}}{{{text}}}%")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"  wrote {out_path}")


# ─────────────────────────────────────────────────────────────────────
# CSV → LaTeX table body
# ─────────────────────────────────────────────────────────────────────
def render_main_gap(csv_path: Path, out_tex: Path, mock: bool) -> None:
    if not csv_path.exists():
        print(f"  (skip {out_tex.name} — {csv_path} missing)")
        return
    rows = list(csv.DictReader(open(csv_path)))
    if not rows:
        print(f"  (skip {out_tex.name} — csv empty)")
        return
    def fmt(v, bold=False):
        if v is None or v == "" or v == "None":
            return r"\mockval{--}" if mock else "--"
        out = v
        if mock: out = f"\\mockval{{{out}}}"
        if bold: out = f"\\textbf{{{out}}}"
        return out
    body = []
    body.append(r"\toprule")
    body.append(r" & & & \multicolumn{3}{c|}{\textbf{Attribution}} "
                r"& \multicolumn{2}{c|}{\textbf{Propagation}} "
                r"& \multicolumn{3}{c|}{\textbf{Accumulation}} & \\")
    body.append(r"\textbf{Model} & \textbf{Acc.} & \textbf{Split} "
                r"& \textbf{Pass@1} & \textbf{Bl@1} & \textbf{Bl@3} "
                r"& \textbf{Out-$G$} & \textbf{RegR.} "
                r"& \textbf{AvgT.} & \textbf{Reps.} & \textbf{Slope} & \textbf{Gap} \\")
    body.append(r"\midrule")
    for r in rows:
        # one row per (model, split)
        body.append(f"{r['model']} & local & {r['split']} & "
                    f"{fmt(r['pass1'])} & {fmt(r['blame1'])} & {fmt(r['blame3'])} & "
                    f"{fmt(r['out_g'])} & {fmt(r['reg_rate'])} & "
                    f"{fmt(r['avg_turns'])} & {fmt(r['repeats'])} & "
                    f"{fmt(r['slope'])} & {fmt(r['gap'])} \\\\")
    body.append(r"\bottomrule")
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text("\n".join(body))
    print(f"  wrote {out_tex}")


def render_fault_family(csv_path: Path, out_tex: Path) -> None:
    if not csv_path.exists():
        return
    rows = list(csv.DictReader(open(csv_path)))
    body = [r"\toprule",
            r"\textbf{Family} & \textbf{Easy-Med} & \textbf{Hard} "
            r"& \textbf{VeryHard+} & \textbf{Total} \\",
            r"\midrule"]
    for r in rows:
        body.append(f"{r['family'].replace('_', ' ').title()} & "
                    f"{r['easy_med']} & {r['hard']} & "
                    f"{r['very_hard_plus']} & {r['total']} \\\\")
    body.append(r"\bottomrule")
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text("\n".join(body))
    print(f"  wrote {out_tex}")


# ─────────────────────────────────────────────────────────────────────
# main
# ─────────────────────────────────────────────────────────────────────
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default="pipeline.yaml")
    ap.add_argument("--analysis-dir", type=Path, required=True)
    ap.add_argument("--paper-dir", type=Path, required=True)
    ap.add_argument("--mock", action="store_true")
    args = ap.parse_args()

    # numbers.json source: real or mock
    if args.mock:
        bundle_path = args.analysis_dir / "mock_bundle.json"
        if not bundle_path.exists():
            sys.exit(f"missing {bundle_path}")
        bundle = json.load(open(bundle_path))
        # synthesize numbers dict from mock bundle
        numbers = {
            "n_models": 6,
            "n_full_problems": 818,
            "n_hard_problems": 128,
            "outside_g_r":     bundle["tab_diffusion_validation"]["r"],
            "outside_g_n":     bundle["tab_diffusion_validation"]["n"],
            "outside_g_p":     bundle["tab_diffusion_validation"]["p_value"],
            "outside_g_ci_lo": bundle["tab_diffusion_validation"]["r_ci"][0],
            "outside_g_ci_hi": bundle["tab_diffusion_validation"]["r_ci"][1],
        }
        csv_main_gap = None  # built from mock bundle below if needed
    else:
        nj = args.analysis_dir / "analysis" / "numbers.json"
        if not nj.exists():
            sys.exit(f"missing {nj}. Run `make analyze`.")
        numbers = json.load(open(nj))
        csv_main_gap = args.analysis_dir / "tables" / "main_gap_table.csv"

    # numbers.tex
    render_numbers(numbers, args.paper_dir / "numbers.tex", mock=args.mock)

    # tables/
    if csv_main_gap and csv_main_gap.exists():
        render_main_gap(csv_main_gap,
                        args.paper_dir / "tables" / "tab_main_gap.tex",
                        mock=args.mock)
    render_fault_family(args.analysis_dir / "tables" / "fault_family_distribution.csv",
                        args.paper_dir / "tables" / "tab_fault_family.tex")

    print("\nDone. Now run `make check` to verify consistency.")


if __name__ == "__main__":
    main()
